backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
locale: es
collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - label: "Inicio"
        name: "home"
        file: "src/content/home.md"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Descripción", name: "description", widget: "text"}
          - {label: "Imagen Hero", name: "hero", widget: "image"}
      - label: "Sobre mí"
        name: "about"
        file: "src/content/about.md"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Contenido", name: "body", widget: "markdown"}
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen destacada", name: "image", widget: "image"}
      - {label: "Contenido", name: "body", widget: "markdown"}
